version: 20.10.24
services:
  mysqlserver:
    image: mysql:8.0.23
    enviroment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=productos
    ports:
      - 3306:3306
  product-server:
    build:
      context: .
    ports:
      - 8082:8082
    environment:
      - MYSQL_URL=jdbc:mysql://mysqlserver/integradorOstric-security
